version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    depends_on:
      - php
    networks:
      - api-bonus

  php:
    build: .
    container_name: php
    volumes:
      - .:/var/www/html
    networks:
      - api-bonus
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pgsql_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - api-bonus

networks:
  api-bonus:
    driver: "bridge"

volumes:
  postgres-data:
